spring:
  application:
    name: spring-data-jpa

  datasource:
    url: jdbc:mysql://localhost:3306/spring-data
#    username: postgres
    username: mehrab
    password: zaq123ZAQ!@#

  jpa:
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop